# -*- coding: utf-8 -*-
"""Vídeo 4 — una escena por marca de tiempo. Estilo pixel sobrio.

Regla de escritura: cada escena es una relación física entre objetos presentes.
Las personas van como figuras norteafricanas, piel morena, ropa real del suceso
y expresión neutra. Nunca caricatura.
"""

GUION = [
 ("0-00","En solo veinticuatro horas, una ciudad de ochenta mil habitantes","Wide aerial view of a small coastal city of white apartment blocks pressed between a mountain and the sea, quiet and ordinary."),
 ("0-05","recibió una llegada masiva de setenta y dos mil personas.","The same coastal city seen from the sea, now with an enormous crowd of small figures covering the rocks and slopes below the buildings."),
 ("0-10","Pero lo más increíble no fue cuánta gente cruzó la frontera.","A tall border fence seen from the side, with a huge crowd on one side of it, drawn small."),
 ("0-15","Sino quién dejó de vigilarla.","An empty guard post beside a border fence, its door open and nobody inside, seen straight on."),
 ("0-19","La invasión de Ceuta del treinta de julio","A concrete breakwater at night with many people in the water around its end, the lit city behind."),
 ("0-23","es el mayor episodio en la frontera entre España y Marruecos","A simple map view: two land masses separated by a narrow strait, with a small enclave marked on the African side."),
 ("0-28","desde que esa frontera existe.","An old stone border marker standing alone on dry ground, weathered, with a fence line behind it."),
 ("0-31","Y no la paró nadie.","A long stretch of border fence with nobody standing along it, empty ground on both sides."),
 ("0-34","No hubo disparos. No hubo tanques.","A rifle and a tank drawn simply side by side, each with a large red cross over it, on plain ground."),
 ("0-38","La mayoría entró nadando.","Many heads of swimmers in dark sea water at night, moving towards a lit shoreline."),
 ("0-41","Rodeando un espigón de hormigón que se mete en el mar.","A long concrete breakwater seen from above, extending into the water, with a line of swimmers curving around its far end."),
 ("0-46","Y aquí viene la pregunta que casi nadie hace.","A large red question mark standing on the beach beside the end of a breakwater."),
 ("0-50","¿Cómo puede ocurrir una invasión así","A border fence with a huge crowd pressed against it, seen from a distance under a hazy sky."),
 ("0-54","en una frontera de la Unión Europea?","A ring of small stars drawn on a plain blue panel fixed to a border post beside the fence."),
 ("0-58","La respuesta no está en Marruecos.","A red arrow pointing away from a large land mass on the right, curving instead towards a small enclave on the coast."),

 ("1-02","Empecemos por lo que pasó exactamente.","A plain wall calendar with one date circled in red, hanging beside a window that looks onto the sea."),
 ("1-06","Ceuta es una ciudad española en el norte de África.","A small city of white buildings on a narrow neck of land, with sea on both sides and mountains behind."),
 ("1-10","Ochenta mil habitantes. Diecinueve kilómetros cuadrados.","A tiny patch of built up land drawn beside a much larger empty landscape, for scale."),
 ("1-15","Rodeada por Marruecos por tierra y por el Mediterráneo por mar.","The same small city with a fence line drawn along its whole land side and open water on the other."),
 ("1-20","Es, junto a Melilla, la única frontera terrestre","Two small marked points on a long coastline, everything else along the coast left blank."),
 ("1-24","entre la Unión Europea y África.","A simple map with a narrow strait between two continents, and a thin line running along the coast."),
 ("1-27","El treinta de julio, por la tarde, empezó a llegar gente.","A coastal road in late afternoon light with a scattering of people walking along it towards the city."),
 ("1-32","Primero cientos. Luego miles.","The same road, now filled from edge to edge with people walking in the same direction."),
 ("1-35","En una sola noche, decenas de miles.","Night. An enormous crowd of small figures spread across a rocky shoreline under street lights."),
 ("1-39","El Ministerio del Interior cifró la invasión","A plain government building facade with a podium and microphones outside it, nobody speaking."),
 ("1-43","en setenta y dos mil personas.","A vast crowd filling the entire frame edge to edge, drawn as thousands of tiny figures."),
 ("1-46","Ponlo en perspectiva.","A pair of simple scales, one pan holding a small cluster of figures and the other an enormous one."),
 ("1-48","Es como si en tu ciudad, esta noche,","An ordinary residential street at night, quiet, with lit windows and parked cars."),
 ("1-52","apareciera casi tanta gente como la que ya vive en ella.","The same street completely filled with people, from the doorways to the far end."),
 ("1-57","Y no entraron saltando la valla.","A tall border fence standing intact, undamaged, with nobody on it."),
 ("2-00","La valla aguantó.","A close view of the fence posts firmly in the ground, unbent, with the ground undisturbed at their base."),
 ("2-02","Entraron por el agua.","A stretch of dark sea beside the end of a fence, with many swimmers in it."),
 ("2-05","Bordeando a nado el espigón del Tarajal,","A concrete breakwater seen from the side at water level, with swimmers passing around its outer tip."),
 ("2-09","que es donde la frontera deja de ser valla y pasa a ser mar.","A fence running down a beach and simply ending where the water begins, with open sea beyond."),
 ("2-14","Ahí no hay nada que saltar.","The last fence post standing at the water's edge with nothing beyond it but waves."),
 ("2-17","Solo hay que nadar unos metros.","A short stretch of water between the end of the breakwater and the shore, with a swimmer crossing it."),

 ("2-21","Ahora la parte que explica la invasión de verdad.","A hand lifting a corner of a map to reveal a second layer underneath."),
 ("2-26","Y no es agradable.","A plain closed door with a heavy lock, seen straight on in dim light."),
 ("2-28","Esa frontera, sobre el papel, la vigila España.","A border post with a Spanish flag on a pole beside it, red and yellow horizontal bands."),
 ("2-33","Guardia Civil, Policía Nacional, cámaras, vallas.","Four things in a row: two uniformed figures seen from behind, a camera on a pole, and a section of fence."),
 ("2-38","Pero en la práctica hay un segundo filtro,","Two fences drawn one behind the other, with a strip of ground between them."),
 ("2-42","y está del otro lado.","A red arrow pointing to the far fence, the one further from the city."),
 ("2-44","Marruecos.","A Moroccan flag on a pole against a plain sky, red with a green star in the centre."),
 ("2-46","Durante años, España y Marruecos han cooperado","Two flags on poles side by side, Spanish and Moroccan, with a handshake drawn simply between them."),
 ("2-50","para que la gente no llegue siquiera a la frontera.","A road checkpoint far from any fence, with a barrier across it and vehicles stopped."),
 ("2-54","Marruecos pone controles en las carreteras.","A barrier across a country road with a small guard cabin beside it and cars queueing."),
 ("2-57","Vigila las playas de su lado.","An empty beach at dawn with a patrol vehicle parked on the sand and two figures walking the shoreline."),
 ("3-00","Y disuelve las concentraciones antes de que se formen.","A small group of people on open ground being approached by uniformed figures, before any crowd has formed."),
 ("3-04","A cambio recibe dinero, material y apoyo diplomático.","Three things flowing along an arrow: a bag of money, a stack of equipment crates, and a signed document."),
 ("3-09","Sobre el papel es cooperación.","A signed agreement lying on a desk with two pens beside it."),
 ("3-12","En la práctica, España delegó una parte del control","A key being handed from one hand to another across a border line drawn on the ground."),
 ("3-16","de su propia frontera en un país extranjero.","A house with its front door being guarded by a figure standing outside the fence of the neighbouring property."),
 ("3-20","Y ahí está el problema.","A red exclamation mark standing beside that door."),
 ("3-22","Porque si tu puerta la vigila tu vecino,","Two adjacent houses, with the guard of the second house standing at the door of the first."),
 ("3-26","tu vecino decide cuándo está vigilada.","The same door, now unattended, with the neighbour walking away from it."),

 ("3-31","El treinta de julio, los controles marroquíes","A road checkpoint with its barrier raised and the guard cabin empty."),
 ("3-35","no estuvieron donde suelen estar.","An empty stretch of road where a checkpoint used to be, with only the painted markings left on the tarmac."),
 ("3-38","Marruecos ha dicho que la situación no era querida,","A podium with microphones and a Moroccan flag behind it, nobody at the podium."),
 ("3-42","que fue cosa de bulos y de redes de tráfico de personas,","A phone screen glowing in a dark street, with many other small screens glowing behind it."),
 ("3-47","y ha cooperado después en los retornos.","A line of coaches parked along a road with people boarding them in an orderly queue."),
 ("3-51","Puede ser exactamente así.","A balance scale perfectly level, both pans empty."),
 ("3-53","Pero el efecto es el mismo,","Two different roads that both end at the same open gate."),
 ("3-56","y el efecto es lo que importa.","A red arrow pointing at the open gate, ignoring the roads behind it."),
 ("3-59","Cuando el filtro marroquí no está,","Two fences drawn one behind the other, the far one simply missing, leaving a gap."),
 ("4-02","la frontera española se queda sola.","A single fence line standing alone with wide empty ground on both sides."),
 ("4-05","Y sola no aguanta.","The same single fence with an enormous crowd pressed along its whole length."),
 ("4-08","Esto ya había pasado antes.","A wall calendar with two dates circled in red, several pages apart."),
 ("4-11","En dos mil veintiuno entraron varios miles de personas en Ceuta","A crowd on a beach beside a breakwater, large but clearly smaller than the later one, in daylight."),
 ("4-16","en pleno pulso diplomático entre los dos países.","Two flags on poles leaning away from each other, the ropes between them taut."),
 ("4-20","Entonces se leyó como un aviso.","A single warning lamp glowing amber on an otherwise dark control panel."),
 ("4-23","Cinco años después, la cifra se multiplica por diez.","Two crowds side by side, the right one ten times the size of the left, both drawn as tiny figures."),

 ("4-29","Y aquí conviene entender qué quiere Marruecos.","A Moroccan flag on a pole with a red arrow curving out from it towards the south."),
 ("4-33","Marruecos tiene una prioridad diplomática por encima de todas.","A stack of documents with one single sheet pulled out and placed on top of the pile."),
 ("4-38","El Sáhara Occidental.","A wide empty desert landscape with dunes and a single unmarked border line drawn across the sand."),
 ("4-40","Quiere que el mundo reconozca su soberanía sobre ese territorio.","A globe on a stand with many small flags planted around it, all leaning towards one desert region."),
 ("4-45","Y usa lo que tiene para conseguirlo.","A hand resting on a large lever mounted on the ground."),
 ("4-48","Lo que tiene es una posición geográfica","A narrow strait between two continents seen from above, with a small enclave on the southern coast."),
 ("4-51","y el control de un flujo de personas.","A valve on a wide pipe, with many small figures flowing through the pipe towards it."),
 ("4-54","En dos mil veintidós, España cambió su postura histórica","A signed letter on a desk beside a Spanish flag, with an older document pushed to one side."),
 ("4-59","sobre el Sáhara Occidental y se alineó con la marroquí.","Two flags on poles now leaning the same way, the Spanish beside the Moroccan."),
 ("5-04","El giro se anunció sin debate público previo.","An empty parliament chamber with rows of vacant seats and a lit podium at the front."),
 ("5-08","Y no fue gratis. Nada de esto es gratis.","A price tag hanging from the corner of a signed document."),
 ("5-12","Cuando una relación se apoya en que el otro te haga un favor,","One figure holding up a heavy beam that rests on the shoulder of a second figure."),
 ("5-17","ese favor tiene precio.","A price tag hanging from that beam."),
 ("5-19","Y el precio se revisa.","The same price tag with the old number scratched out and a larger tag hanging beside it."),
 ("5-22","Cada vez que Marruecos quiere algo,","A hand reaching for the lever again, in the same position as before."),
 ("5-25","tiene una palanca que no necesita ejércitos.","A large lever standing alone on open ground, with a tank drawn small beside it and a red cross over the tank."),
 ("5-29","Le basta con mirar hacia otro lado durante unas horas.","A guard post with the figure inside turned to face away from the fence, looking out of the opposite window."),

 ("5-35","La segunda parte del problema está dentro de España.","A map of a country with a red arrow pointing inward from its own coast."),
 ("5-39","Porque una cosa es que falle el filtro de fuera.","A missing fence panel leaving a gap in an otherwise complete fence line."),
 ("5-43","Otra es no tener capacidad de reacción.","An empty emergency control room with dark screens and vacant chairs."),
 ("5-47","Cuando empezaron a llegar había unos setecientos agentes.","A small group of uniformed figures standing in a line on a wide open esplanade."),
 ("5-52","Se reforzó hasta poco más de mil.","The same line of figures slightly longer, still small against the wide esplanade."),
 ("5-55","Mil agentes para setenta y dos mil personas.","A thin line of uniformed figures facing an enormous crowd that fills the rest of the frame."),
 ("5-59","Y no es solo un problema de números.","A calculator lying on the ground with a red cross drawn over it."),
 ("6-02","Es que una ciudad de ochenta mil habitantes","A small city of white apartment blocks seen from above, compact and finite."),
 ("6-05","no tiene sitio, ni comida, ni camas","Three empty things in a row: an empty square, an empty food crate and an empty camp bed."),
 ("6-09","para absorber a setenta y dos mil personas de golpe.","A city square completely filled with people, with more still arriving from every street."),
 ("6-13","Ningún plan lo contemplaba.","An open folder on a desk with its pages blank."),
 ("6-16","Casi todos volvieron a Marruecos en los días siguientes.","A long queue of people walking back along a coastal road towards a border gate in the distance."),
 ("6-20","A cuatro de agosto, Interior cifraba en setenta mil los retornos.","A wall calendar with a later date circled, and a queue of coaches drawn beside it."),
 ("6-25","Pero eso no es un mérito del Estado.","A medal lying face down on a table with a red cross drawn over it."),
 ("6-28","Es que la mayoría cruzó por algo que no existía","A phone screen glowing in the dark with nothing on it, held in a hand."),
 ("6-32","y al comprobarlo se dio la vuelta.","A crowd of small figures on a shoreline, all turned around and walking back the way they came."),
 ("6-35","Si se hubieran quedado, no había plan para eso.","An empty city square at night with a single folded camp bed left standing in the middle of it."),
 ("6-39","Y dos semanas después, ante el rumor de que podía repetirse,","A phone screen glowing in a dark street again, with more screens lighting up behind it."),
 ("6-44","España y Marruecos desplegaron más de cuatro mil seiscientos agentes.","A very long double line of uniformed figures stretching along both sides of a border fence to the horizon."),
 ("6-50","Cuatro veces más para prevenir que para responder.","Two lines of figures side by side, the right one four times longer than the left."),

 ("6-55","Y falta la tercera pata: Europa.","A three legged stool with its third leg drawn in a different colour from the other two."),
 ("6-59","Ceuta no es solo una frontera española.","A fence line with a Spanish flag on one post and a blue starred panel on the next."),
 ("7-02","Es la frontera exterior de la Unión Europea.","A long line drawn around the edge of a continent, with one short segment of it on the far coast highlighted in red."),
 ("7-06","Quien cruza ahí, entra en Europa.","A gate in a fence with an arrow passing through it and continuing far into the land beyond."),
 ("7-09","Pero cuando ocurrió la invasión,","A crowd pressed along a fence line seen from above, filling the frame."),
 ("7-12","la Unión Europea no lo trató como un problema europeo.","A large meeting room with a round table and many empty chairs, one single chair occupied."),
 ("7-16","Lo trató como un problema español.","A single figure standing alone holding up a heavy beam, with a row of seated figures watching from a distance."),
 ("7-19","Y su preocupación principal fue otra:","A red arrow curving away from a coastal fence and pointing north into the interior of a continent."),
 ("7-22","que no se extendiera hacia dentro.","A second fence being built inland, far from the coast, facing the wrong way."),
 ("7-25","Que no llegara al resto del continente.","A map of a continent with a red line drawn across its middle, and a small enclave left outside it."),
 ("7-28","O sea: arregladlo vosotros, y que no nos salpique.","A door being closed from the inside, with one figure left standing outside it."),
 ("7-33","España pone la frontera.","A single figure holding a long fence panel upright on its own."),
 ("7-35","Europa recibe el beneficio de que esa frontera exista.","A group of figures sitting comfortably behind that fence, at a distance from it."),
 ("7-39","Y cuando falla, el problema es de España.","The fence panel fallen over with only the single figure beside it, the group still seated far behind."),

 ("7-45","Y aquí está lo que de verdad enseña esta historia.","An open book lying on a stone wall with a border fence visible behind it."),
 ("7-49","Un Estado se define por muy pocas cosas.","Three simple icons in a row: a fence, a coin and a court gavel."),
 ("7-53","Una de ellas es controlar quién entra en su territorio.","A gate with a single figure standing beside it, hand raised, deciding who passes."),
 ("7-58","Si esa función la sostiene otro país,","That same gate, with the deciding figure now standing on the far side of a second fence."),
 ("8-02","no es que la hayas compartido.","Two hands each holding one half of a broken key."),
 ("8-04","Es que se la has prestado.","One hand holding a whole key, extended away from an open empty hand."),
 ("8-07","Y quien te la guarda decide cuándo devolverla.","A closed hand holding a key behind its back, with a door standing shut in front."),
 ("8-11","Es lo mismo que vimos con los chips y con Alemania.","Three objects in a row on a shelf: a black chip, a small steam locomotive and a border fence panel."),
 ("8-16","Depender de alguien no se nota mientras cumple.","One figure holding up a heavy beam steadily, another standing relaxed beneath it."),
 ("8-20","Se nota el día que deja de cumplir.","The first figure stepping away, the beam falling towards the second."),
 ("8-24","Piénsalo en tu trabajo. En tu empresa. En tu vida.","A plain desk with a lamp and a chair, standing alone in an empty room."),
 ("8-29","Qué cosa importante estás dando por hecho","A single load bearing pillar in the middle of an empty room, holding up the ceiling."),
 ("8-32","solo porque nunca ha fallado.","A close view of the base of that pillar, with a hairline crack running through it."),

 ("8-36","Ceuta no cayó por la fuerza.","A border fence standing completely intact and undamaged in the morning light."),
 ("8-39","Cayó porque durante unas horas","An empty guard post beside that intact fence, its door open and the chair inside vacant."),
 ("8-42","nadie estaba haciendo lo que se daba por supuesto.","The same guard post seen wider, with the fence stretching away in both directions and nobody along it."),
 ("8-46","Si quieres ver hasta dónde llega esto de depender de otro,","A black chip and a small steam locomotive resting side by side on a stone wall."),
 ("8-51","te lo cuento en el vídeo que tienes en pantalla.","An empty video player frame with a triangular play button, standing on the same stone wall."),
]

if __name__ == "__main__":
    ids = [g[0] for g in GUION]
    print(f"escenas: {len(GUION)}")
    print(f"duplicados: {len(ids) - len(set(ids))}")
