# -*- coding: utf-8 -*-
"""Vídeo 2 — una escena por marca de tiempo, con su estilo.

Estilos: "sob" = pixel sobrio · "ale" = pixel alegre

Estructura: sobrio en el gancho, alegre en el flashback de los años buenos
(1:00-3:30), sobrio a partir de 3:35 cuando caen las tres patas.

Regla de escritura: cada escena es una relación física entre objetos presentes.
Nada de ausencias, negaciones ni «lo que podría haber sido» — eso el pixel art
no lo dibuja. Ver estilos/README.md.
"""

# (marca, estilo, texto hablado, escena dibujada)
GUION = [
 ("0-00","sob","Hay un país en Europa que fabricaba el motor de todo lo demás.","A huge iron engine block on a factory floor, with belts and shafts running from it out to machines on both sides."),
 ("0-03","sob","Sus coches. Sus máquinas. Las fábricas de otros países.","Three things lined up on a factory floor: a car, a big industrial machine, and a small model of a whole factory."),
 ("0-07","sob","Durante veinte años fue la envidia del continente.","A large factory complex on a hill, and below it small distant figures standing in a row all turned towards it."),
 ("0-10","sob","Le llamaban la locomotora de Europa.","A powerful steam locomotive pulling a long line of loaded wagons, smoke trailing behind it across an industrial landscape."),
 ("0-13","sob","Hoy esa locomotora está parada.","The same locomotive standing still on rusted rails, no smoke from its chimney, weeds growing between the sleepers."),
 ("0-16","sob","No va lenta. Está parada.","A close view of a locomotive wheel completely still on the rail, with a thick chain wrapped around it and grass growing around the wheel."),
 ("0-19","sob","Y lo raro no es que se haya parado.","A stopped locomotive with its boiler intact and undamaged, no dents, no broken parts, simply motionless."),
 ("0-22","sob","Lo raro es cómo.","A magnifying glass held over the still wheel of the locomotive, showing the rail underneath perfectly intact."),
 ("0-24","sob","No cambió de estrategia. No se equivocó de rumbo.","A single straight railway track running dead straight to the horizon with no curves and no junctions."),
 ("0-28","sob","Siguió haciendo exactamente lo mismo que la hizo rica.","A locomotive on that same straight track with a long trail of identical wagons stretching behind it into the distance."),
 ("0-32","sob","Y eso, de repente, dejó de funcionar.","The straight track ending abruptly at the edge of the frame where the rails simply stop, with the locomotive halted just before the end."),
 ("0-35","sob","Peor: empezó a hundirla.","The locomotive sinking, its wheels half buried in mud that has risen over the rails."),
 ("0-38","sob","Y aquí viene la pregunta que casi nadie se hace.","One large question mark shape built out of railway track pieces, standing upright in an empty factory yard."),
 ("0-41","sob","¿Cómo puede arruinarte lo mismo que te hizo rico?","One enormous golden gear wheel with a heavy iron chain running from it to the ankle of a small figure leaning forward, straining to walk away and unable to move."),
 ("0-45","sob","La respuesta explica por qué Alemania no puede arreglarlo sin más.","A small figure with a spanner standing in front of an enormous machine that towers over it, the spanner tiny against one huge bolt."),
 ("0-50","sob","Y por qué te afecta aunque no vivas allí.","A factory in the distance and a red thread running from its door all the way to an ordinary house in the foreground."),
 ("0-54","sob","Porque cuando la locomotora se para,","A stopped locomotive at the front of a long train, seen from the side."),
 ("0-57","sob","el resto del tren tampoco avanza.","The same long train seen from above, every single wagon behind the locomotive standing still on the track."),

 ("1-00","ale","Empecemos por lo que hacía tan bien.","A bright clean factory with three tall chimneys, seen from the front under a blue sky."),
 ("1-03","ale","El modelo alemán se apoyaba en tres patas.","A large sturdy table standing on exactly three thick legs, with a shining factory model on top of it."),
 ("1-07","ale","Nada más. Tres.","The same three legged table alone in an empty green field, seen clearly from the side."),
 ("1-09","ale","La primera: gas ruso barato.","A large blue gas flame burning steadily under an industrial boiler, with a fat pipe feeding it from the left."),
 ("1-12","ale","Muy barato. Y llegaba casi todo por el mismo sitio.","One single very thick pipe running across the whole frame from left to right, feeding one factory."),
 ("1-16","ale","Por el Nord Stream, un tubo bajo el mar Báltico.","A cutaway view of the sea: a long pipeline lying on the seabed under blue water, running from a coast on the left to a coast on the right, with a ship sailing above it."),
 ("1-19","ale","La segunda: China.","A Chinese national flag on a pole in front of a large modern factory, plain red with five yellow stars in the upper left corner."),
 ("1-24","ale","Un país que crecía sin parar y necesitaba máquinas.","A city skyline under construction, cranes everywhere, new buildings rising in every direction."),
 ("1-28","ale","Máquinas de Siemens y de mil fábricas alemanas más","A row of big industrial machines with gears and pistons, lined up on a loading dock ready to be shipped."),
 ("1-31","ale","para construir sus propias fábricas.","A cargo ship loaded with crated machines sailing away from a European port towards a distant Asian skyline."),
 ("1-34","ale","La tercera: el motor de explosión.","A detailed cutaway of a combustion engine showing pistons, valves and crankshaft, drawn clean and bright."),
 ("1-38","ale","Volkswagen, BMW, Mercedes, Porsche, Audi.","Five cars of different shapes parked in a neat row on a bright forecourt, each with a round metal badge on its grille."),
 ("1-41","ale","Un siglo perfeccionando el mismo motor.","A workbench with the same engine repeated five times across it, each one slightly more refined and polished than the last."),
 ("1-45","ale","Ahí no competía nadie.","One car on a winners podium, and the second and third places on the podium standing completely empty."),
 ("1-47","ale","Junta las tres y tienes la fórmula.","The three legged table again, now with a gas flame, a cargo ship and an engine standing one on each leg."),
 ("1-50","ale","Energía barata para fabricar.","A gas flame under a boiler with a small price tag hanging from the pipe, the tag tiny."),
 ("1-53","ale","Un cliente gigante que te compra.","One enormous open hand reaching in from the right side of the frame, receiving a small crate from a factory on the left."),
 ("1-56","ale","Y un producto que nadie sabe hacer igual.","A gleaming engine standing on a display pedestal under a spotlight in a bright hall."),
 ("1-59","ale","Durante veinte años, esa fórmula fue imbatible.","A long line of cargo ships sailing out of a port one behind the other, all fully loaded."),
 ("2-04","ale","Alemania exportaba más de lo que importaba, año tras año.","A balance scale on a dock: the side stacked with outgoing crates hangs much lower than the side with incoming ones."),
 ("2-09","ale","Acumulaba dinero mientras media Europa se endeudaba.","A tall neat stack of gold coins on the left and several much smaller crooked stacks on the right, all on the same table."),
 ("2-14","ale","Y todo el mundo quería copiarla.","A group of small figures standing around the three legged table, each one sketching it on a notepad."),

 ("2-20","ale","Ahora la parte incómoda.","The three legged table seen from below, one of its legs showing a hairline crack near the base."),
 ("2-23","ale","Esa fórmula funcionaba tan bien que nadie la tocó.","The three legged table inside a glass display case, sealed, with a velvet rope around it."),
 ("2-27","ale","Y cuando algo funciona, no lo cuestionas.","Small figures standing guard in a ring around the glass case, all facing outwards."),
 ("2-31","ale","Lo defiendes.","The same glass case now surrounded by a low protective fence with the figures still standing around it."),
 ("2-33","ale","Mientras tanto, el mundo hacía otras cosas.","Behind the fenced case, in the background, cranes are building completely different structures."),
 ("2-37","ale","Otros países metían dinero en software.","A bright new building with a large screen on its facade showing rows of coloured squares, and coins flowing into its door."),
 ("2-40","ale","En redes. En baterías. En chips.","Three new buildings side by side: one with antennas on the roof, one with a big battery cell outside, one with a black chip on its wall."),
 ("2-44","ale","Alemania metía dinero en lo que ya sabía hacer.","Coins flowing into the door of the old brick factory with the three chimneys."),
 ("2-48","ale","Más máquinas. Mejores motores.","A workshop packed with more machines and more engines than before, all polished and lined up."),
 ("2-51","ale","Y le salía bien. Los números le daban la razón cada trimestre.","A wall chart with a line climbing steadily upwards, and small figures below it looking pleased."),
 ("2-56","ale","Es la trampa más difícil de ver.","A wooden animal trap standing wide open in a sunny meadow, with a shining gold coin resting on its plate."),
 ("2-59","ale","No es que se equivocaran.","A neat row of correct green ticks marked along the edge of a long paper roll."),
 ("3-01","ale","Es que acertaban tanto que no miraron a otro lado.","A figure in blinkers facing straight ahead at a machine, while behind it on both sides new buildings rise unseen."),
 ("3-06","ale","A eso se le llama depender del éxito.","A locomotive moving forward on a track, while behind it the rails it has already passed are ripped up and stacked in a heap."),
 ("3-09","ale","Cuanto mejor te va, más caro es cambiar.","A balance scale where one side holds a tall stack of coins and the other holds a small steering wheel that cannot lift it."),
 ("3-13","ale","Y menos ganas tienes.","A figure sitting comfortably in an armchair on top of a pile of coins, feet up."),
 ("3-15","ale","Un país entero apostó veinte años a lo mismo.","A huge pile of coins and crates all stacked onto one single square on a giant board."),
 ("3-19","ale","Con sus fábricas, sus universidades, sus contratos.","Three buildings connected to each other by thick cables: a factory, a university with columns, and an office."),
 ("3-24","ale","Todo alineado en una única dirección.","Dozens of arrows on the ground all pointing the same way, perfectly parallel."),
 ("3-27","ale","Eso da una fuerza enorme.","A single enormous arrow made of many small arrows fused together, driving forward."),
 ("3-30","ale","Y también hace que girar sea casi imposible.","The same enormous arrow trying to bend, cracking along its length as it does."),

 ("3-35","sob","Entonces, en muy poco tiempo, cayeron las tres patas.","The three legged table with all three legs snapped, the factory model on top tipping over, under a grey overcast sky."),
 ("3-40","sob","Casi a la vez.","Three broken table legs lying together on the ground, all snapped at the same height."),
 ("3-42","sob","La primera fue el gas.","A gas burner under an industrial boiler with the flame gone out, only a thin wisp of smoke left."),
 ("3-45","sob","En 2022 Rusia invadió Ucrania y el Nord Stream se cerró.","A large valve wheel on a thick pipeline, turned fully shut, with the pipe beyond it empty and cold."),
 ("3-48","sob","De un día para otro, el gas barato dejó de ser barato.","A price tag hanging from a gas pipe, now enormous compared to the small tag that hangs beside it."),
 ("3-52","sob","Y las fábricas que lo necesitaban se encontraron con la factura.","A long paper bill unrolling out of a factory door and spilling across the whole yard."),
 ("3-57","sob","No un poco más alta. Varias veces más alta.","Two paper bills pinned side by side on a wall, the right one many times longer than the left, reaching the floor."),
 ("4-01","sob","Cuando fabricas acero, vidrio o productos químicos,","Three industrial buildings side by side: one with a glowing furnace, one with glass sheets stacked, one with chemical tanks."),
 ("4-05","sob","la energía no es un gasto más.","A pie shaped stack of crates where one enormous crate takes up almost the whole pile and the rest are tiny."),
 ("4-08","sob","Es casi todo el coste.","A steel beam resting on a scale, and on the other side one huge gas cylinder outweighing it completely."),
 ("4-10","sob","Y si tu vecino la tiene más barata, ya no puedes competir.","Two factories side by side across a border fence, the left one with a huge price tag on its pipe and the right one with a tiny tag."),
 ("4-15","sob","Algunas fábricas no subieron precios.","A factory gate with a heavy padlock on it and no smoke from the chimneys behind."),
 ("4-18","sob","Simplemente pararon.","An empty factory floor with cold machines, tools left on the benches and nobody there."),
 ("4-20","sob","La segunda pata fue China.","A Chinese flag on a pole in front of a large modern factory under a grey sky."),
 ("4-23","sob","Terminó de construir sus fábricas.","A finished industrial complex with all its cranes lowered and parked at the edge of the site."),
 ("4-28","sob","Y entonces hizo algo que nadie había previsto.","A factory door opening from the inside, with crates coming out instead of going in."),
 ("4-30","sob","Empezó a fabricar ella lo que antes compraba.","Two identical machines standing side by side, one in front of a European brick factory and one in front of a modern Asian factory."),
 ("4-34","sob","Coches incluidos.","A line of identical new cars coming off an assembly line inside a large modern plant."),
 ("4-38","sob","BYD vende hoy más coches eléctricos que Tesla.","Two stacks of cars on a dock, the left stack clearly taller than the right one, both loaded onto the same cargo ship."),
 ("4-41","sob","El cliente se convirtió en competidor.","Two identical factories facing each other across grey water, both with chimneys smoking and identical container stacks, an empty cargo ship motionless between them."),
 ("4-43","sob","Y fabrica más barato y en más cantidad.","Two price tags side by side, the right one much smaller, hanging over two stacks of crates where the right stack is much taller."),
 ("4-47","sob","Y la tercera pata fue el coche.","A car standing alone in an empty yard with its bonnet open, under a grey sky."),
 ("4-50","sob","Durante un siglo, el motor de explosión fue una obra de arte.","A combustion engine displayed on a pedestal in a museum hall, roped off like a sculpture."),
 ("4-55","sob","Miles de piezas encajando a la perfección.","An exploded view of an engine with hundreds of small parts floating in ordered rows around it."),
 ("4-58","sob","Nadie lo hacía como ellos.","The same engine on its pedestal with empty pedestals on both sides."),
 ("5-01","sob","El coche eléctrico tiene muchas menos piezas.","An exploded view of an electric motor with only a handful of large simple parts floating around it."),
 ("5-05","sob","Muchísimas menos.","Two workbenches side by side: the left covered edge to edge in small parts, the right holding just three large ones."),
 ("5-07","sob","Y de repente, un siglo de ventaja vale mucho menos.","A tall trophy shelf full of engine parts, with a price tag on it that has been crossed out and replaced by a much smaller one."),
 ("5-12","sob","Lo que Alemania sabía hacer mejor que nadie","A polished combustion engine held up on a stand in a workshop."),
 ("5-15","sob","dejó de ser lo importante.","The same engine pushed to the corner of the workshop, dusty, with a sheet half over it."),
 ("5-18","sob","Ahora lo importante es la batería.","One large battery cell standing upright in the centre of an empty factory floor, lit from above."),
 ("5-21","sob","Y la batería se fabrica sobre todo en otro sitio.","A battery cell on a dock beside a Chinese flag, with a cargo ship waiting behind it."),
 ("5-25","sob","Tres patas. Tres golpes.","Three broken table legs standing upright in the ground like posts, each snapped at the top."),
 ("5-28","sob","Y ninguno de los tres se veía venir desde dentro.","A figure inside a factory looking out through a small dirty window, unable to see the yard beyond."),

 ("5-35","sob","Esto no es una previsión. Ya está pasando.","A wall calendar with today's date circled in red, hanging in an empty factory office."),
 ("5-39","sob","La economía alemana lleva años sin crecer.","A wall chart with a line that runs completely flat from left to right."),
 ("5-43","sob","No en caída libre. Parada.","The same flat line on the chart, with a small figure standing on top of it as if on level ground."),
 ("5-46","sob","Que para un país que vivía de exportar es lo mismo.","A cargo ship sitting motionless at a dock with its cranes idle and no containers moving."),
 ("5-50","sob","BASF, la mayor química del mundo, ha cerrado líneas en Ludwigshafen.","A vast chemical plant with tanks and pipes along a river, one whole section of it dark and shut while the rest still runs."),
 ("5-56","sob","Y ha montado una planta nueva en China.","A brand new chemical plant with clean white tanks, and a Chinese flag on a pole beside it."),
 ("6-00","sob","Y una vez que una fábrica se muda, no vuelve.","An empty concrete slab where a factory used to stand, with only the bolt holes left in the ground."),
 ("6-04","sob","Volkswagen anunció recortes.","The front of a German car with its round VW badge on the grille, parked inside an empty factory hall."),
 ("6-08","sob","Y se planteó cerrar plantas en Alemania.","A large factory gate with a chain across it and a German flag hanging still on a pole beside it."),
 ("6-12","sob","Cosa que no había pasado en sus casi noventa años de historia.","A long row of framed photographs along a corridor wall, all of them full factories, and the last frame on the wall empty."),
 ("6-15","sob","Los pedidos de máquinas industriales han caído.","An order book lying open on a desk with its pages blank, in an empty office."),
 ("6-19","sob","Y cuando caen los pedidos de máquinas,","A machine standing finished on a loading dock with no truck waiting for it."),
 ("6-22","sob","es que nadie está construyendo fábricas nuevas.","An empty construction site with foundations poured and cranes parked and still."),
 ("6-26","sob","Es el indicador que avisa antes que ningún otro.","A single warning lamp glowing red on an otherwise dark control panel."),
 ("6-30","sob","Mientras tanto, los que sí fabrican baterías crecen.","A large modern battery plant with cranes still building new wings onto it."),
 ("6-35","sob","Los que fabrican software crecen.","A modern glass office building rising with construction cranes around it and screens glowing in the windows."),
 ("6-38","sob","Los que tienen energía barata crecen.","A power plant with cables running out to a busy factory beside it, both fully lit."),
 ("6-41","sob","Alemania mira desde fuera cómo crecen los demás","A figure standing alone outside a tall wire fence, looking through it at construction cranes working on the other side."),
 ("6-45","sob","haciendo justo lo que ella decidió no hacer.","On the near side of the same fence, a rolled up set of plans lying unopened on the ground."),

 ("6-55","sob","Y aquí está lo que hace que esto no se arregle rápido.","A large hourglass standing on a desk in a factory office, most of the sand already fallen."),
 ("6-59","sob","El diagnóstico lo tienen. Lo sabe todo el mundo allí.","A thick bound report lying open on a meeting table with figures standing around it."),
 ("7-04","sob","Los informes están escritos.","A shelf packed with identical bound reports, all spines lined up."),
 ("7-06","sob","El problema no es saber qué pasa.","One report open on the table with a clear diagram visible on the page."),
 ("7-09","sob","El problema es que arreglarlo tarda años.","A wall calendar with many pages, and a long arrow running across all of them from left to right."),
 ("7-13","sob","Construir una fábrica de baterías tarda años.","A half built battery plant with only its steel frame standing, cranes around it."),
 ("7-17","sob","Formar a los técnicos que la manejan tarda años.","A classroom with rows of desks and one machine at the front, students seated in front of it."),
 ("7-21","sob","Cambiar lo que enseñan las universidades tarda años.","A university building with columns, and workers carrying an old engine out of the front door while a battery cell waits outside."),
 ("7-25","sob","Y montar una red eléctrica distinta tarda más todavía.","A landscape crossed by half finished electricity pylons, the cables hanging loose between the last two."),
 ("7-30","sob","Todo eso se puede hacer.","A toolbox open on the ground with all its tools laid out neatly beside it."),
 ("7-32","sob","Pero no se puede hacer deprisa.","The same toolbox with a large hourglass standing on top of it."),
 ("7-35","sob","Mientras tanto, los competidores no esperan.","Two runners on a track seen from the side, one far ahead of the other and still moving."),
 ("7-39","sob","Es el mismo problema que vimos con los chips.","One black rectangle chip and one battery cell standing side by side on the same table."),
 ("7-43","sob","No es un problema de dinero. Es de tiempo acumulado.","A bag of coins on one side of a scale and an hourglass on the other, the hourglass side hanging much lower."),

 ("7-46","sob","Y aquí está lo que de verdad enseña esta historia.","An open book lying on a workbench with a small lamp lit above it."),
 ("7-49","sob","Lo más peligroso no es hacerlo mal.","A machine part lying broken on a bench with a red cross marked beside it."),
 ("7-52","sob","Es hacerlo demasiado bien durante demasiado tiempo.","A gleaming polished machine part on a pedestal, so worn smooth by polishing that its edges have disappeared."),
 ("7-57","sob","Porque el éxito te da razones para no cambiar.","A trophy shelf full of cups, with a locked door directly behind it."),
 ("8-01","sob","Y cada año que aciertas, cambiar cuesta más.","A steering wheel with more and more chains added to it in layers, each layer thicker than the last."),
 ("8-05","sob","Alemania no se durmió.","A factory with every window lit and workers visible inside, at night."),
 ("8-07","sob","Estuvo trabajando muchísimo. En lo de siempre.","The same lit factory producing an enormous stack of identical engines in the yard outside."),
 ("8-11","sob","Piénsalo en lo que haces tú.","A single ordinary desk with a lamp and a chair, standing alone in an empty room."),
 ("8-13","sob","En qué eres muy bueno desde hace mucho.","One tool on that desk, worn smooth and shiny from decades of use."),
 ("8-16","sob","Y pregúntate si sigue importando tanto como antes.","The same worn tool lying beside a brand new tool of a completely different shape."),

 ("8-20","sob","Alemania no perdió porque alguien la adelantara.","A steam locomotive running steadily along its rails, polished and working perfectly, completely alone on the track with no other train anywhere near it."),
 ("8-24","sob","Perdió porque el mundo cambió de pregunta.","The railway track simply ends in the grass, and right beside it runs a new electrified line with overhead cables, where a modern train is already moving."),
 ("8-28","sob","Y ella seguía dando la mejor respuesta a la anterior.","The steam locomotive still running immaculately along its own short piece of old track, alone, while the electrified line beside it carries traffic in both directions."),
 ("8-32","sob","Si quieres ver la otra cara de esto, un sitio que sí sigue siendo insustituible, te lo cuento en el vídeo que tienes en pantalla.","One small green island alone in blue water with a black chip resting on it, and beside it an empty video player frame with a triangular play button."),
]

if __name__ == "__main__":
    ids = [g[0] for g in GUION]
    print(f"escenas: {len(GUION)}")
    print(f"duplicados: {len(ids) - len(set(ids))}")
    print(f"sobrio: {sum(1 for g in GUION if g[1] == 'sob')}")
    print(f"alegre: {sum(1 for g in GUION if g[1] == 'ale')}")
